CREATE TABLE CATEGORIA (
    ID_CATEGORIA        NUMBER NOT NULL ,
    NOMBRE              VARCHAR2(100) NOT NULL,
    DESCRIPCION         VARCHAR2(500),
    FECHA_CREACION      DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION  DATE,
    CONSTRAINT  pk_id_categoria PRIMARY KEY (ID_CATEGORIA)
);
COMMENT ON  TABLE CATEGORIA IS 'Tabla que contiene la informacion del Categorias';
COMMENT ON COLUMN CATEGORIA.ID_CATEGORIA IS 'LLave primaria de la tabla Categorias';
COMMENT ON COLUMN CATEGORIA.NOMBRE IS 'Campo del nombre de la categoria';
COMMENT ON COLUMN CATEGORIA.DESCRIPCION IS 'Campo de la descripcion de categoria';
COMMENT ON COLUMN CATEGORIA.FECHA_CREACION IS 'Campo de control que indica la Fecha de creacion en la BD';
COMMENT ON COLUMN CATEGORIA.FECHA_MODIFICACION IS 'Campo de control que indica la Accion de registro';

CREATE TABLE CATEGORIA_BIT(
    ID_CATEGORIA_BIT NUMBER NOT NULL,
    ID_CATEGORIA        NUMBER NOT NULL,
    NOMBRE              VARCHAR2(100) NOT NULL,
    DESCRIPCION         VARCHAR2(500),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(10)NOT NULL,
    IP VARCHAR2(30)NOT NULL,
    CONSTRAINT pk_id_categoria_bit_ PRIMARY KEY (ID_CATEGORIA_BIT),
    CONSTRAINT fk_categoria_id_categoria FOREIGN KEY (ID_CATEGORIA) REFERENCES  CATEGORIA(ID_CATEGORIA)
);

COMMENT ON  TABLE  CATEGORIA_BIT IS 'Tabla de Bitacora que contiene las Categoria';
COMMENT ON  COLUMN CATEGORIA_BIT.ID_CATEGORIA_BIT IS 'LLave primaria de la tabla CATEGORIA_BIT';
COMMENT ON  COLUMN CATEGORIA_BIT.ID_CATEGORIA IS 'LLave foranea ID_CATEGORIA que hace referencia a la tabla CATEGORIA';
COMMENT ON  COLUMN CATEGORIA_BIT.NOMBRE IS 'Campo del nombre de la categoria';
COMMENT ON  COLUMN CATEGORIA_BIT.FECHA_CREACION IS 'Campo de control que indica la Fecha de creacion en la BD';
COMMENT ON  COLUMN CATEGORIA_BIT.FECHA_MODIFICACION IS 'Campo de control que indica la Accion de registro';
COMMENT ON  COLUMN CATEGORIA_BIT.ACCION IS 'Campo de control que indica la Accion en el Registro';
COMMENT ON  COLUMN CATEGORIA_BIT.IP IS 'Campo de control que indica IP de donde se solicito operacion en el Registro';


CREATE TABLE PRODUCTO(
    ID_PRODUCTO  NUMBER NOT NULL,
    NOMBRE              VARCHAR2(150) NOT NULL,
    PRECIO              NUMBER(10,2) NOT NULL CHECK (PRECIO >= 0),
    STOCK               NUMBER(10) DEFAULT 0 CHECK (STOCK >= 0),
    ID_CATEGORIA        NUMBER NOT NULL,
    DESCRIPCION         VARCHAR2(500),
    ESTATUS             VARCHAR2(20) DEFAULT 'ACTIVO',
    FECHA_CREACION      DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION  DATE,
    CONSTRAINT pk_id_producto PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT fk_producto_id_categoria FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);
COMMENT ON  TABLE PRODUCTO IS 'Tabla que contiene la informacion de productos';
COMMENT ON COLUMN PRODUCTO.ID_PRODUCTO IS 'LLave primaria de la tabla productos';
COMMENT ON COLUMN PRODUCTO.NOMBRE IS 'Campo del nombre de producto';
COMMENT ON COLUMN PRODUCTO.PRECIO IS 'Precio Unitario del producto';
COMMENT ON COLUMN PRODUCTO.STOCK IS 'Campo que indica cuanto prodcutos hay en existencia';
COMMENT ON COLUMN PRODUCTO.ID_CATEGORIA IS 'LLave Foranea  que hace referencia a la tabla CATEGORIAS';
COMMENT ON COLUMN PRODUCTO.DESCRIPCION IS 'Campo que describe el producto';
COMMENT ON COLUMN PRODUCTO.ESTATUS IS 'Campo de control el estado del producto (Activo,Inactivo)';
COMMENT ON COLUMN PRODUCTO.FECHA_CREACION IS 'Campo de control que indica la Fecha de creacion en la BD';
COMMENT ON COLUMN PRODUCTO.FECHA_MODIFICACION IS 'Campo de control que indica la Accion de registro';

CREATE TABLE PRODUCTO_BIT(
    ID_PRODUCTO_BIT      NUMBER NOT NULL ,
    ID_PRODUCTO         NUMBER NOT NULL,
    NOMBRE              VARCHAR2(150) NOT NULL,
    PRECIO              NUMBER(10,2) NOT NULL,
    STOCK               NUMBER(10) DEFAULT 0,
    ID_CATEGORIA        NUMBER NOT NULL,
    DESCRIPCION         VARCHAR2(500),
    ESTATUS             VARCHAR2(20) DEFAULT 'ACTIVO',
    FECHA_CREACION      DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION  DATE,
    ACCION VARCHAR2(10)NOT NULL,
    IP VARCHAR2(30)NOT NULL,
    CONSTRAINT pk_id_producto_bit PRIMARY KEY (ID_PRODUCTO_BIT ),
    CONSTRAINT fk_producto_bit_id_producto FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    CONSTRAINT fk_categoria_bit_id_categoria FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);
COMMENT ON  TABLE PRODUCTO_BIT IS 'Tabla que contiene la informacion de producto_bit';
COMMENT ON COLUMN PRODUCTO_BIT.ID_PRODUCTO_BIT IS 'LLave primaria de la tabla ID_PRODUCTO_BIT';
COMMENT ON COLUMN PRODUCTO_BIT.ID_PRODUCTO IS 'LLave primaria de la tabla productos';
COMMENT ON COLUMN PRODUCTO_BIT.NOMBRE IS 'Campo del nombre de producto';
COMMENT ON COLUMN PRODUCTO_BIT.PRECIO IS 'Precio Unitario del producto';
COMMENT ON COLUMN PRODUCTO_BIT.STOCK IS 'Campo que indica cuanto prodcutos hay en existencia';
COMMENT ON COLUMN PRODUCTO_BIT.ID_CATEGORIA IS 'LLave Foranea  que hace referencia a la tabla CATEGORIAS';
COMMENT ON COLUMN PRODUCTO_BIT.DESCRIPCION IS 'Campo que describe el producto';
COMMENT ON COLUMN PRODUCTO_BIT.ESTATUS IS 'Campo de control el estado del producto (Activo,Inactivo)';
COMMENT ON COLUMN PRODUCTO_BIT.FECHA_CREACION IS 'Campo de control que indica la Fecha de creacion en la BD';
COMMENT ON COLUMN PRODUCTO_BIT.FECHA_MODIFICACION IS 'Campo de control que indica la Accion de registro';
COMMENT ON COLUMN PRODUCTO_BIT.ACCION IS 'Campo de control que indica la Accion en el Registro';
COMMENT ON COLUMN PRODUCTO_BIT.IP IS 'Campo de control que indica IP de donde se solicito operacion en el Registro';


CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(100)NOT NULL,
    APELLIDOS VARCHAR2(150)NOT NULL,
    CORREO VARCHAR2(150) UNIQUE  NOT NULL,
    TELEFONO VARCHAR2(15) NOT NULL ,
    FECHA_REGISTRO DATE DEFAULT  SYSDATE,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    CONSTRAINT pk_id_cliente PRIMARY KEY (ID_CLIENTE)
);

COMMENT ON TABLE CLIENTE IS 'Tabla que contiene la informacion de los clientes';
COMMENT ON COLUMN CLIENTE.ID_CLIENTE IS 'Llave primary key tabla del cliente';
COMMENT ON COLUMN CLIENTE.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTE.APELLIDOS IS 'Apellidos del cliente';
COMMENT ON COLUMN CLIENTE.CORREO IS 'Correo electronico del cliente';
COMMENT ON COLUMN CLIENTE.TELEFONO IS 'Numero de telefono del cliente';
COMMENT ON COLUMN CLIENTE.FECHA_REGISTRO IS 'Fecha en que el cliente se registro';
COMMENT ON COLUMN CLIENTE.FECHA_CREACION IS 'Campo de control que indica la Fecha de creacion en la BD';
COMMENT ON COLUMN CLIENTE.FECHA_MODIFICACION IS 'Campo de control que indica la Accion de registro';

CREATE TABLE CLIENTE_BIT(
    ID_CLIENTE_BIT NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(100)NOT NULL,
    APELLIDOS VARCHAR2(150)NOT NULL,
    CORREO VARCHAR2(150) UNIQUE  NOT NULL,
    TELEFONO VARCHAR2(15) NOT NULL ,
    FECHA_REGISTRO DATE DEFAULT  SYSDATE,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(10)NOT NULL,
    IP VARCHAR2(30)NOT NULL,
    CONSTRAINT pk_id_cliente_bit PRIMARY KEY (ID_CLIENTE_BIT),
    CONSTRAINT fk_id_cliente_cliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

COMMENT ON TABLE CLIENTE_BIT IS 'Tabla que contiene la informacion de los cliente_bit';
COMMENT ON COLUMN CLIENTE_BIT.ID_CLIENTE IS 'Llave primary key tabla del cliente';
COMMENT ON COLUMN CLIENTE_BIT.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTE_BIT.APELLIDOS IS 'Apellidos del cliente';
COMMENT ON COLUMN CLIENTE_BIT.CORREO IS 'Correo electronico del cliente';
COMMENT ON COLUMN CLIENTE_BIT.TELEFONO IS 'Numero de telefono del cliente';
COMMENT ON COLUMN CLIENTE_BIT.FECHA_REGISTRO IS 'Fecha en que el cliente se registro';
COMMENT ON COLUMN CLIENTE_BIT.FECHA_CREACION IS 'Campo de control que indica la Fecha de creacion en la BD';
COMMENT ON COLUMN CLIENTE_BIT.FECHA_MODIFICACION IS 'Campo de control que indica la Accion de registro';
COMMENT ON COLUMN CLIENTE_BIT.ACCION IS 'Campo de control que indica la Accion en el Registro';
COMMENT ON COLUMN CLIENTE_BIT.IP IS 'Campo de control que indica IP de donde se solicito operacion en el Registro';


CREATE TABLE VENTA (
    ID_VENTA NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER(10),
    FECHA_VENTA DATE DEFAULT SYSDATE,
    USUARIO_REGISTRO VARCHAR2(100)NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICAION DATE,
    CONSTRAINT pk_id_venta PRIMARY KEY (ID_VENTA),
    CONSTRAINT fk_cliente_id_cliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT fk_producto_id_producto FOREIGN KEY (ID_PRODUCTO) REFERENCES  PRODUCTO(ID_PRODUCTO)
);

COMMENT ON TABLE VENTA IS 'Tabla que registra las ventas realizadas';
COMMENT ON COLUMN VENTA.ID_VENTA IS 'Identificador unico de la venta';
COMMENT ON COLUMN VENTA.ID_CLIENTE IS 'Identificador del cliente que realiza la compra';
COMMENT ON COLUMN VENTA.ID_PRODUCTO IS 'Identificador del producto vendido';
COMMENT ON COLUMN VENTA.CANTIDAD IS 'Cantidad de productos vendidos';
COMMENT ON COLUMN VENTA.FECHA_VENTA IS 'Fecha en que se realizo la venta';
COMMENT ON COLUMN VENTA.USUARIO_REGISTRO IS 'Usuario que registro la venta en el sistema';

CREATE TABLE VENTA_BIT (
    ID_VENTA_BIT        NUMBER NOT NULL,
    ID_VENTA            NUMBER NOT NULL,
    ID_CLIENTE          NUMBER NOT NULL,
    ID_PRODUCTO         NUMBER NOT NULL,
    CANTIDAD            NUMBER(10),
    FECHA_VENTA         DATE DEFAULT SYSDATE,
    USUARIO_REGISTRO    VARCHAR2(100)NOT NULL,
    FECHA_CREACION      DATE DEFAULT SYSDATE,
    FECHA_MODIFICAION   DATE,
    ACCION VARCHAR2(10)NOT NULL,
    IP VARCHAR2(30)NOT NULL,
    CONSTRAINT pk_id_venta_bit PRIMARY KEY (ID_VENTA_BIT),
    CONSTRAINT fk_id_venta_venta_bit FOREIGN KEY  (ID_VENTA) REFERENCES  VENTA(ID_VENTA),
    CONSTRAINT fk_id_cliente_venta_bit FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT fk_id_producto_venta_bit FOREIGN KEY (ID_PRODUCTO) REFERENCES  PRODUCTO(ID_PRODUCTO)
);

COMMENT ON TABLE  VENTA_BIT IS 'Tabla que registra las ventas realizadas';
COMMENT ON COLUMN VENTA_BIT.ID_VENTA_BIT IS '';
COMMENT ON COLUMN VENTA_BIT.ID_VENTA IS 'Identificador unico de la venta';
COMMENT ON COLUMN VENTA.ID_CLIENTE IS 'Identificador del cliente que realiza la compra';
COMMENT ON COLUMN VENTA.ID_PRODUCTO IS 'Identificador del producto vendido';
COMMENT ON COLUMN VENTA.CANTIDAD IS 'Cantidad de productos vendidos';
COMMENT ON COLUMN VENTA.FECHA_VENTA IS 'Fecha en que se realizo la venta';
COMMENT ON COLUMN VENTA.USUARIO_REGISTRO IS 'Usuario que registro la venta en el sistema';
COMMENT ON COLUMN CLIENTE_BIT.ACCION IS 'Campo de control que indica la Accion en el Registro';
COMMENT ON COLUMN CLIENTE_BIT.IP IS 'Campo de control que indica IP de donde se solicito operacion en el Registro';


--Creacion Secuencias para las llaves primarias (PK'S)
CREATE SEQUENCE  SEC_ID_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE ;
CREATE SEQUENCE  SEC_ID_PRODUCTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE  SEC_ID_CLIENTE START WITH  1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE  SEC_ID_VENTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEC_ID_CATEGORIA_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_PRODUCTO_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_CLIENTE_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_VENTA_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/
select * from VENTA;