
CREATE OR REPLACE VIEW VW_PRODUCTOS_CATEGORIA AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE AS NOMBRE_PRODUCTO,
    P.PRECIO,
    P.STOCK,
    P.ESTATUS,
    C.ID_CATEGORIA,
    C.NOMBRE AS NOMBRE_CATEGORIA,
    C.DESCRIPCION AS DESCRIPCION_CATEGORIA
FROM PRODUCTO P
INNER JOIN CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA;


CREATE OR REPLACE VIEW VW_VENTAS_DETALLE AS
SELECT
    V.ID_VENTA,
    V.FECHA_VENTA,
    C.ID_CLIENTE,
    C.NOMBRE || ' ' || C.APELLIDOS AS CLIENTE,
    P.ID_PRODUCTO,
    P.NOMBRE AS PRODUCTO,
    V.CANTIDAD,
    P.PRECIO,
    (V.CANTIDAD * P.PRECIO) AS TOTAL_VENTA,
    V.USUARIO_REGISTRO
FROM VENTA V
INNER JOIN CLIENTE C ON c.ID_CLIENTE = v.ID_CLIENTE
INNER JOIN PRODUCTO P ON P.ID_PRODUCTO = V.ID_PRODUCTO;


SELECT * FROM VW_PRODUCTOS_CATEGORIA;
