
---Funcion que regresa una ip
CREATE OR REPLACE FUNCTION  FN_GET_IP
RETURN VARCHAR2
IS
BEGIN
    --INTENTO DE OBTENER IP DEL HOST QU HACE CONEXION
    RETURN NVL(SYS_CONTEXT('USERENV','IP_ADDRESS'),SYS_CONTEXT('USERNEV','HOST'));
    EXCEPTION
      WHEN OTHERS THEN
       RETURN 'LOCALHOST';
END FN_GET_IP;
/
---Calcular el total de ventas
CREATE OR REPLACE FUNCTION FN_CALCULAR_TOTAL_VENTA (
    P_ID_VENTA IN NUMBER
)
RETURN NUMBER
IS
    V_CANTIDAD NUMBER(10,2);
    V_PRECIO   NUMBER(10,2);
    V_TOTAL    NUMBER;
BEGIN
    -- Obtener cantidad y precio
    SELECT V.CANTIDAD, P.PRECIO INTO V_CANTIDAD, V_PRECIO
    FROM VENTA V
    INNER JOIN PRODUCTO P
        ON V.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE V.ID_VENTA = P_ID_VENTA;

    -- Calcular total
    V_TOTAL := V_CANTIDAD * V_PRECIO;

    RETURN V_TOTAL;
END FN_CALCULAR_TOTAL_VENTA;
SELECT FN_CALCULAR_TOTAL_VENTA(14)
FROM DUAL;


---Funcion que retorna una estatus
CREATE OR REPLACE FUNCTION FN_GET_ESTATUS (
    P_NOMBRE IN PRODUCTO.NOMBRE%TYPE
)
RETURN VARCHAR2
IS
    V_EXISTE  NUMBER;
    V_STOCK   PRODUCTO.STOCK%TYPE;
    V_ESTATUS PRODUCTO.ESTATUS%TYPE;
BEGIN
    -- Validar si existe el producto
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM PRODUCTO
    WHERE UPPER(NOMBRE) = UPPER(P_NOMBRE);
    IF V_EXISTE = 0 THEN
        RETURN 'ERROR: Producto no existe';
    ELSIF V_EXISTE > 1 THEN
        RETURN 'ERROR: Existen múltiples productos con ese nombre';
    END IF;
    -- Obtener stock y estatus
    SELECT STOCK, ESTATUS
    INTO V_STOCK, V_ESTATUS
    FROM PRODUCTO
    WHERE UPPER(NOMBRE) = UPPER(P_NOMBRE);
    RETURN 'STOCK: ' || V_STOCK || ' | ESTATUS: ' || V_ESTATUS;
END;
/ SELECT * FROM PRODUCTO;
SELECT FN_GET_ESTATUS('Laptop Lenovo') FROM DUAL;


