---Crear tiggers la bitacora de tabla CAtegiroas
CREATE OR REPLACE  TRIGGER  TRG_CATEGORIAS_AIU
AFTER INSERT OR UPDATE ON CATEGORIA FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10) :='';
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN
    IF INSERTING  THEN
        V_ACCION :='INSERT';
        V_FECHA_CREACION := SYSDATE;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_CREACION := SYSDATE;
    END IF;
    INSERT INTO CATEGORIA_BIT (
    ID_CATEGORIA_BIT, ID_CATEGORIA, NOMBRE,
    DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION,ACCION, IP)
    VALUES (SEC_ID_CATEGORIA_BIT.NEXTVAL, :NEW.ID_CATEGORIA,:NEW.NOMBRE,:NEW.DESCRIPCION,
            V_FECHA_CREACION,V_FECHA_MODIFICACION,V_ACCION,FN_GET_IP);
END;

CREATE OR REPLACE  TRIGGER  TRG_PRODUCTOS_AIU
AFTER INSERT OR UPDATE ON PRODUCTO FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10) :='';
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN
    IF INSERTING  THEN
        V_ACCION :='INSERT';
        V_FECHA_CREACION := SYSDATE;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_CREACION := SYSDATE;
    END IF;
    INSERT INTO PRODUCTO_BIT (ID_PRODUCTO_BIT, ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, DESCRIPCION, ESTATUS,
                          FECHA_CREACION, FECHA_MODIFICACION, ACCION, IP)
    VALUES(SEC_ID_PRODUCTO_BIT.NEXTVAL,:NEW.ID_PRODUCTO,:NEW.NOMBRE,:NEW.PRECIO,:NEW.STOCK,:NEW.ID_CATEGORIA
          ,:NEW.DESCRIPCION,:NEW.ESTATUS,V_FECHA_CREACION,V_FECHA_MODIFICACION,V_ACCION,FN_GET_IP);
END;

CREATE OR REPLACE  TRIGGER  TRG_CLIENTE_AIU
AFTER INSERT OR UPDATE ON CLIENTE FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10) :='';
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN
    IF INSERTING  THEN
        V_ACCION :='INSERT';
        V_FECHA_CREACION := SYSDATE;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_CREACION := SYSDATE;
    END IF;
    INSERT INTO CLIENTE_BIT (ID_CLIENTE_BIT, ID_CLIENTE, NOMBRE, APELLIDOS,CORREO, TELEFONO, FECHA_REGISTRO,FECHA_CREACION, FECHA_MODIFICACION, ACCION, IP)
    VALUES (SEC_ID_CLIENTE_BIT.NEXTVAL,:NEW.ID_CLIENTE,:NEW.NOMBRE,:NEW.APELLIDOS,:NEW.CORREO,:NEW.TELEFONO,:NEW.FECHA_REGISTRO,
            V_FECHA_CREACION,V_FECHA_MODIFICACION,V_ACCION,FN_GET_IP);
END;

CREATE OR REPLACE  TRIGGER  TRG_VENTA_AIU
AFTER INSERT OR UPDATE ON VENTA FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10) :='';
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN
    IF INSERTING  THEN
        V_ACCION :='INSERT';
        V_FECHA_CREACION := SYSDATE;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_CREACION := SYSDATE;
    END IF;
    INSERT INTO
    VENTA_BIT (ID_VENTA_BIT, ID_VENTA, ID_CLIENTE, ID_PRODUCTO, CANTIDAD,FECHA_VENTA, USUARIO_REGISTRO,FECHA_CREACION, FECHA_MODIFICAION, ACCION, IP)
    VALUES (SEC_ID_VENTA_BIT.NEXTVAL,:NEW.ID_VENTA,:NEW.ID_CLIENTE,:NEW.ID_PRODUCTO,:NEW.CANTIDAD,:NEW.FECHA_VENTA,:NEW.USUARIO_REGISTRO,
            V_FECHA_CREACION,V_FECHA_MODIFICACION,V_ACCION,FN_GET_IP);
END;


--Crear trigger para el id de la tabla CATEGORIA
CREATE  OR REPLACE  TRIGGER  TRG_CATEGORIA_BI
BEFORE INSERT ON CATEGORIA FOR EACH ROW
BEGIN
    :NEW.ID_CATEGORIA := SEC_ID_CATEGORIA.NEXTVAL;
END;

--Crear trigger para el id de la tabla PRODUCTO
CREATE  OR REPLACE  TRIGGER  TRG_PRODUCTO_BI
BEFORE INSERT ON PRODUCTO FOR EACH ROW
BEGIN
    :NEW.ID_PRODUCTO := SEC_ID_PRODUCTO.NEXTVAL;
END;

--Crear Trigger_para el di de la tabla CLIENTE
CREATE OR REPLACE  TRIGGER  TRG_CLIENTE_BI
BEFORE INSERT ON CLIENTE FOR EACH ROW
BEGIN
   :NEW.ID_CLIENTE := SEC_ID_CLIENTE.NEXTVAL;
END;

--Crear trigger para el id, folio y año de la tabla facturas
CREATE OR REPLACE TRIGGER TRG_VENTA_BI
BEFORE INSERT ON VENTA FOR EACH ROW
BEGIN
    --LLaves primaria
    :NEW.ID_VENTA := SEC_ID_VENTA.NEXTVAL;
END;